[program:hikvision-gateway]
command=/usr/local/bin/hikvision-gateway /var/www/panel_payday_usr/data/www/panel.payday.uz/gateway_config.json
directory=/var/www/panel_payday_usr/data/www/panel.payday.uz
autostart=true
autorestart=true
startsecs=5
user=root
environment=LD_LIBRARY_PATH="/opt/ip-camera-ehome-server/thirdparty/HCISUPSDK/linux64/lib"
redirect_stderr=true
stdout_logfile=/var/log/hikvision-gateway.log
